### ISSUE TITLE
Google Maps Embed Component

### ISSUE THREAD

**Issue by blbergo** [GdscCpp/socal-gd-website#22]
# Task
- create a component that loads a Google Maps embed, that can be used in the GDG and GDSC pages.

## Resources:
- https://www.npmjs.com/package/google-map-react
- https://www.npmjs.com/package/@react-google-maps/api

**Note:** I will create an API key for the project and DM you it and add it to prod later on.

**Comment by Rebeccals** [comment]
Finished
